import type { Metadata } from "next";
import { Abril_Fatface, Poppins } from "next/font/google"; // Importing the fonts
import "./globals.css";

// Importing fonts from Google (but not applying class names directly)
const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-poppins antialiased bg-matchawith">{children}</body>
    </html>
  );
}
